name: mt_pipeline
channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - bwa=0.7.17
  - samtools=1.18
  - bcftools=1.23
  - bedtools=2.31.1
  - mitofinder=1.4.2
  - spades
